### ISSUE TITLE
Some ideas to improve server/compute module

### ISSUE THREAD

**Issue by relaxdiego** [DimensionDataDevOps/ansible-dimensiondata#27]
In trying out the server/compute module, some ideas to improve the API as well as the underlying implementation came to mind. Here's a sampling of the next-gen API than I'm thinking about:

```yaml
- name: Ensure Cluster Hosts
  dimensiondata_compute:
    ensure:         present
    location:       NA12
    network_domain: b1c369b1-f3cc-42b2-ac3f-e674b9d6efc0
    vlans:
                    - b0f4fe04-d843-440d-9813-2393fcf740be
                    - 13756690-ac77-b776-4fc1-f5535cee6f16
    description:    Service X Web Server {N}
    image:          75e25531b1674a917d13557bf43ebf594d624373
    nodes:          "{{groups['webserver']}}"
    admin_password: "{{root_password}}"
    primary_dns:    8.8.8.8
    secondary_dns:  8.8.4.4
    wait:           yes
```

The proposed changes in the API:

1. Rename the `dimensiondata` module to `dimensiondata_server` to make it consistent with the other modules. We can keep the former but depricate it prior to removal.
2. As an alternative to `vlan`, we should also allow `vlans` so that the user can specify 2 or more vlans to attach the server to. Both `vlan` and `vlans` should be made mutually exclusive.
3. Allow an `{N}` marker in the description which will be replaced with index+1 of the server in the `nodes` list. For example, for the first server, `{N}` will be replaced with `1` whereas the second will have `2` and so forth.
4. Add the ability to specify the primary and secondary dns. This will require a change in the underlying libcloud API to support submission os such data to the backend.

The proposed change for the underlying implementation is that the module should launch all servers in sequence BUT without waiting for each server task to complete before proceeding to the next. Instead, the module should start waiting after all commands have been sent to the backend API. This can shave plenty of time for the module because the server provisioning happens in parallel. Otherwise, the user might as well just make use of Ansible's built-in `with_items` feature.

This is a considerable change but I'm willing to work on them if that's cool with the rest of the team.
