### ISSUE TITLE
Need a way to add hosts from inventory as members of load balancer

### ISSUE THREAD

**Issue by relaxdiego** [DimensionDataDevOps/ansible-dimensiondata#30]
Assuming a group named 'masters' in an the inventory, there's currently no way to add them to a load balancer because `for` loops **do not** work in tasks:

```yaml
- name: Create load balancer for masters
  dimensiondata_load_balancer:
    region:         "na"
    location:       "locationuuidhere"
    network_domain: "networkdomainidhere"
    name:           "load balancer 001"
    protocol:       http
    members:
    {% for item in group['masters'] %}
      - name: "{{hostvars['item'].inventory_hostname}}"
        ip:   "{{hostvars['item'].default_ipv4.address}}"
    {% endfor %}
    ensure: present
```

The only way right now is to hard code the members which is not ideal. There must be a way to add a compute to a load balancer. Perhaps we can create the load balancer first and then use its UUID as a parameter in creating a compute:

```yaml
- name: Ensure Cluster Hosts
  dimensiondata_compute:
    ensure:         present
    location:       NA12
    network_domain: b1c369b1-f3cc-42b2-ac3f-e674b9d6efc0
    vlans:
                    - b0f4fe04-d843-440d-9813-2393fcf740be
                    - 13756690-ac77-b776-4fc1-f5535cee6f16
    load_balancer:  LOADBALANCERIDHERE
    description:    Service X Web Server {N}
    image:          75e25531b1674a917d13557bf43ebf594d624373
    nodes:          "{{groups['webserver']}}"
    admin_password: "{{root_password}}"
    primary_dns:    8.8.8.8
    secondary_dns:  8.8.4.4
    wait:           yes
```

**Comment by relaxdiego** [comment]
I found a way by creating a custom filter plugin:

```yaml
def memberlist(mylist):
    return [{'name': i['name'], 'ip': i['private_ipv4'][0]}
            for i in mylist]


class FilterModule(object):

    def filters(self):
        return {
            'memberlist': memberlist
        }
```

And then using that to filter a register generated by another task:

```yaml
dimensiondata_load_balancer:
  members: "{{cluster_masters['results'] | map(attribute='nodes.0') | list | memberlist}}"
  ..
```
